### ISSUE TITLE
building v105.0-1

### ISSUE THREAD

**Issue by ghost** [maltejur/publish_lw_win#1]
Somehow, the $version gets recognized as '105.0' and should probably '105.0-1'. when I patch for this, choco gets done, but winget fails like so:

```
remote: Resolving deltas: 100% (5/5), completed with 4 local objects.
To https://github.com/stanzabird/winget-pkgs.git
 ! [remote rejected]       update_librewolf -> update_librewolf (refusing to allow a Personal Access Token to create or update workflow `.github/workflows/spellCheck.yaml` without `workflow` scope)
error: failed to push some refs to 'https://github.com/stanzabird/winget-pkgs.git'
```

**Comment by ghost** [comment]
This bug remained when doing 105.0.1-1.. also with the same error..

**Comment by maltejur** [comment]
It gets recognized as `105.0` because thats what the git tag on GitLab is called. You should probably just also add the `-1` there.

The winget permission error seems to be something else though. I will fix that.

**Comment by maltejur** [comment]
@stanzabird  Okay the winget error seems to occur because your GitHub access token has the wrong permissions. Go [here](https://github.com/settings/tokens) and add the `workflow` permission to your current token that you are using for the script.

**Comment by ghost** [comment]
Thanks! I updated the token as you said, I'll try it the next release.
